#!/bin/bash
echo "################################################################"
echo "###########################    START      ######################"
echo "################################################################"

echo "We are in START now..."

pacman -S --noconfirm git

git clone https://github.com/ericleman/arch_custom_theme/archive/master.zip --output master.zip

bsdtar -x -f master.zip

cd arch-master

cd arch_install

chmod 777 install.sh

./install.sh $1
