#!/bin/bash
echo "################################################################"
echo "###########################    START      ######################"
echo "################################################################"

echo "We are in START now..."

curl -L https://github.com/ericleman/arch/archive/master.zip --output master.zip

bsdtar -x -f master.zip

cd arch-master

cd arch_install

chmod 777 install.sh

./install.sh $1
